### ISSUE TITLE
Windows install fails

### ISSUE THREAD

**Issue by mgraauw** [proycon/babelente#11]
Hi Maarten, 

Babelente won't install on Windows as is:
Collecting babelente
  Downloading BabelEnte-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Marc\AppData\Local\Temp\pip-build-cagenn93\babelente\setup.py", line 22, in <module>
        long_description=read('README.rst'),
      File "C:\Users\Marc\AppData\Local\Temp\pip-build-cagenn93\babelente\setup.py", line 10, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "c:\programs\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3922: character maps to <undefined>

This is a common issue on Windows, caused by utf-8 characters in README.rst which setup.py tries to interpret as CP1252. Replacing the curly quotes in README.rst with straight quotes solved the issue for me.

Regards,

Marc

**Comment by proycon** [comment]
Thanks for the report: I committed a fix that makes the encoding of the README more explicit so it should hopefully work on Windows too now. Could you give it a try perhaps? (I have no Windows computers myself)

**Comment by mgraauw** [comment]
Fixed indeed!
