### ISSUE TITLE
overlapping entities

### ISSUE THREAD

**Issue by Irishx** [proycon/babelente#3]
Can we adjust Babelpy to only return the longest or best match entity? Is this already solvable with the parameter 'cands=TOP' ?  See http://babelfy.org/guide

**Comment by proycon** [comment]
@irishx: Can you try run an experiment whether ``--cands TOP`` already resolves this?

**Comment by Irishx** [comment]
nope it does not:   example with cands=TOP:
 
           "text": "natural",
            "text": "natural order",
            "text": "order",
            "text": "order of",

**Comment by proycon** [comment]
Okay, then I'll need to implement it myself

**Comment by proycon** [comment]
First version implemented

**Comment by proycon** [comment]
**Summary**: I added an ``--overlap`` parameter that can be configured how to resolve overlapping entities, values are:
 * ``allow`` (default)
 * ``longest`` - Use the longest entity (measured in characters)
 * ``score``/``globalscore``/``coherencescore`` - Use the entity maximising the specified score (as returned  by BabelFy)
