### ISSUE TITLE
subtle scoring implementation issue /comparison Wikfier

### ISSUE THREAD

**Issue by Irishx** [proycon/babelente#5]
The Entity translation recall of a text expresses the number of correctly translated Wikipedia entities in comparison to the overall number of present Wikipedia entities.

example PT
Again Running Back Wilson did not make it happen.
Novamente corrida para trás Wilson não fez acontecer.   (constructed erroneous translation)

en-found link:
https://en.wikipedia.org/wiki/Running_Back

pt missing link:
https://pt.wikipedia.org/wiki/Running_Back

Lets assume the erroneous translation could have lead to  wikipage that is not equivalent  So https://pt.wikipedia.org/wiki/Corrida
This is not possible with the Wikifier implementation, as our focus on the English entities only as our groundtruth: how many of those can we retrieve?

#compute entity translation recall

#computing wikipedia target language coverage
How many of the found Engish topics have an equivalent page in target language?

my $wiki_target_coverage = $nbrSynsets / ($nbrSynsets+$missed);

#scoring of entity translation recall

$entity_translation_recall= $foundpairs / ($nbrSynsets);

-how many of the LANG entities for which we actually know that there exists a corresponding Wikipedia page do we retrieve in the text?

#practical implementation is this:
How many of the entities that have an corresponding LANGLINK wikidia page, can we actually find in the LANG text/lemmas (=matching found pairs)? 

-a subtle difference question is: how many of the  LANG Entities with a wikipedia page that we found in LANG text, actually match with a correspondig wiki-page in English?

a)  total of found pairs (en-lang) in text / total nbr of LANG retrieved wiki-links in text (incl erroneous one) 

vs 

 b) total of found pairs (en-lang) in text / total of possible pairs (en-lang) of wikipedia 

Door de manier van implementeren doe ik nu optie b), we nemen Engels als groundtruth.

bij Babely hebben we een andere manier van entities vinden en kunnen we zowel a) als b) berekenen.

dus laten we ze alebei implementeren zodat we ze ook kunnen vergelijken.

**Comment by Irishx** [comment]
* changing **the recall computing:**
to comute option b) 
for every found en source-entity -> check in babelnet if there exists a equivalent link in target language (babelnet does not cover every item in all languages)
this gives us a hypothetical /upperbound set of target synsets


* **as final output print,**
also add as final output some counts: #lines #matches  #source entities #targetentities en #upperboud-target

**Comment by Irishx** [comment]
the usage of sets

Now set() function is used for the source and target entities and only unique items are counted --> if an entity occurs twice in the same sentence, we only count this once.
This is not wrong, but a design choice with consequences. good to remember and explicitly denote this choice.

**Comment by proycon** [comment]
I implemented some things, however, the recall computation doesn't work yet because the remote API doesn't seem to return any translations anymore. May be an issue on their side even... I exceeded my key limit for today so it's hard to test now :/

**Comment by proycon** [comment]
Debug example: 

```DEBUG getsynset id=bn:00088764v,filterLangs=pt                                                                                                                                                                                                                 
{                                                                                                                                                                                                                                                              
    "senses": [],                                                                                                                                                                                                                                              
    "synsetSource": "WN",                                                                                                                                                                                                                                      
    "wnOffsets": [                                                                                                                                                                                                                                             
        {
            "mapping": {
                "WN_171": [
                    "02075915v"
                ],
                "WN_30": [
                    "02636810v"
                ],
                "WN_16": [
                    "01799837v"
                ],
                "WN_20": [
                    "02558395v"
                ],
                "WN_21": [
                    "02611459v"
                ],
                "WN_15": [
                    "01491797v"
                ]
            },
            "version": "WN_30",
            "id": "wn:02636810v",
            "pos": "VERB",
            "source": "WN"
        }
    ],
    "glosses": [],
    "examples": [],
    "images": [],
    "synsetType": "CONCEPT",
    "categories": [],
    "translations": {},
    "domains": {},
    "lnToCompound": {},
    "lnToOtherForm": {},
    "filterLangs": [],
    "bkeyConcepts": false
}
```

Expecting senses not be empty (at least for some), they are all empty now... even in filterLangs=IT example on http://babelnet.org/guide ...

**Comment by proycon** [comment]
seems to work now, needs some more testing

**Comment by Irishx** [comment]
de berekening van macro recall en prec, nul items worden niet meegeteld

        if targetsynsets:
            precision = len(matches)/len(targetsynsets)
            overallprecision.append(precision)

dus als targetsynsets 0 is, dan doet tie niet mee, met als gevolg deze tellingen:

compute prec 187.2555278871454  / 679
 compute recall 199.96641750062798  / 673
 compute coverage souce 685  targe 685

volgens mij zou je altijd total aantal items moeten gebruiken?

**Comment by proycon** [comment]
Oeps, inderdaad.. de bug zat bij precisie ook!

**Comment by proycon** [comment]
I added the new evaluation method *in a separate git branch* ``newevaluation`` for now so you can compare it against the old one. It's a quick implementation so has to be tested carefully still.
