### ISSUE TITLE
offset problem

### ISSUE THREAD

**Issue by Irishx** [proycon/babelente#6]
why does the  resolveoffset function not work?

Babelente/lib/python3.6/site-packages/babelente/babelente.py", line 52, in resolveoffset
    raise ValueError("Unable to resolve offset " + str(offset))
ValueError: Unable to resolve offset 1783

im testing with  PT file now:

/vol/bigdata2/datasets2/TraMOOC/Data/Wikifier2017/Tune/PT/*sentences

**Comment by proycon** [comment]
do you know the exact file it fails on? Can you paste the command you used (parameters and such)? Then I can try to reproduce it.

**Comment by proycon** [comment]
(reproduces)

**Comment by proycon** [comment]
Should be solved now
