### ISSUE TITLE
printing wishlist

### ISSUE THREAD

**Issue by Irishx** [proycon/babelente#9]
Besides the scores and the full JSON output, it would be very helpful to get a focused list of the matchting pairs like this:

printing a list of all matching items (tab separated):
sentence-nr babelsynsetid source-text-id target-text-id
684 bn:00019586n classroom Klassenraum

I added some code example to babelente.py but I do not know how exactly the entities are structured.

**Comment by proycon** [comment]
Implemented (to stderr)
